// import necessary module
import http from "k6/http";
import { check } from "k6";

  export const options = { // punto de ruptura
    scenarios: {
    breakpoint: {
    executor: 'ramping-arrival-rate', // Incrementa la carga exponencial
    preAllocatedVUs: 100, //VUs alocados inicialmente
    maxVUs: 1e7, //VUs maximo
    stages: [
    { duration: '1m', target: 1000 }, // just slowly ramp-up to a HUGE load
    ]
    }
    },
};  

// ejecutar  k6 run --out web-dashboard=export=report-test.html breakPoint.js
export default function () {

    // define URL and payload
    const url = "http://localhost:8080/medico/1";

    // send a post request and save response as a variable
    const res = http.get(url);

    // Log the request body
    //console.log(res.body);

    // check that response is 200
    check(res, {
        "response code was 200": (res) => res.status == 200,
    });
    //sleep(1);
}
/*
net/fd_posix.go:37 +0x32 fp=0xc03f811190 sp=0xc03f811160 pc=0x22aa32
net.socket({0x1dae918, 0xc029d32fc0}, {0x19ed61e, 0x3}, 0x2, 0x1, 0xc03f8112e8?, 0x0, {0x1db5df8, 0x0}, ...)
        net/sock_posix.go:71 +0x2c8 fp=0xc03f811238 sp=0xc03f811190 pc=0x2443a8
net.internetSocket({0x1dae918, 0xc029d32fc0}, {0x19ed61e, 0x3}, {0x1db5df8, 0x0}, {0x1db5df8?, 0xc03a167cb0?}, 0x1, 0x0, ...)
        net/ipsock_posix.go:167 +0x1e5 fp=0xc03f8112c0 sp=0xc03f811238 pc=0x235005
net.(*sysDialer).doDialTCPProto(0xc03a10fd40, {0x1dae918, 0xc029d32fc0}, 0x0, 0xc03a167cb0, 0x0)
        net/tcpsock_posix.go:85 +0xe7 fp=0xc03f811370 sp=0xc03f8112c0 pc=0x247ea7
net.(*sysDialer).doDialTCP(...)
        net/tcpsock_posix.go:75
net.(*sysDialer).dialTCP(0xc03a167cb0?, {0x1dae918?, 0xc029d32fc0?}, 0x166dd20?, 0xc03f811448?)
        net/tcpsock_posix.go:71 +0x69 fp=0xc03f8113b0 sp=0xc03f811370 pc=0x247d49
net.(*sysDialer).dialSingle(0xc03a10fd40, {0x1dae918, 0xc029d32fc0}, {0x1da5628, 0xc03a167cb0})
        net/dial.go:721 +0x3ce fp=0xc03f811480 sp=0xc03f8113b0 pc=0x2224ae
net.(*sysDialer).dialSerial(0xc03a10fd40, {0x1dae918, 0xc029d32fc0}, {0xc02f24e3e0?, 0x1, 0xc03a167c80?})
        net/dial.go:686 +0x24e fp=0xc03f811588 sp=0xc03f811480 pc=0x221c8e
net.(*sysDialer).dialParallel(0x0?, {0x1dae918?, 0xc029d32fc0?}, {0xc02f24e3e0?, 0x1747280?, 0x19edf53?}, {0x0?, 0x19ed61e?, 0xc0368cb290?})
        net/dial.go:587 +0x3a7 fp=0xc03f8117a0 sp=0xc03f811588 pc=0x221367
net.(*Dialer).DialContext(0xc0398d4620, {0x1dae8a8, 0xc039c42690}, {0x19ed61e, 0x3}, {0xc0368cb2a0, 0xe})
        net/dial.go:578 +0x6ac fp=0xc03f811910 sp=0xc03f8117a0 pc=0x220bac
go.k6.io/k6/lib/netext.(*Dialer).DialContext(0xc0398d4620, {0x1dae8a8, 0xc039c42690}, {0x19ed61e, 0x3}, {0xc0368cb270?, 0xd01f8?})
        go.k6.io/k6/lib/netext/dialer.go:64 +0x7d fp=0xc03f811978 sp=0xc03f811910 pc=0xa432fd
go.k6.io/k6/lib/netext.(*Dialer).DialContext-fm({0x1dae8a8?, 0xc039c42690?}, {0x19ed61e?, 0xc03a167a70?}, {0xc0368cb270?, 0xc01a3bfa18?})
        <autogenerated>:1 +0x49 fp=0xc03f8119c0 sp=0xc03f811978 pc=0x1498529
net/http.(*Transport).dial(0x0?, {0x1dae8a8?, 0xc039c42690?}, {0x19ed61e?, 0xfffffffffffffffe?}, {0xc0368cb270?, 0xc01a3bfa10?})
        net/http/transport.go:1278 +0xd2 fp=0xc03f811a28 sp=0xc03f8119c0 pc=0x385712
net/http.(*Transport).dialConn(0xc0381824e0, {0x1dae8a8, 0xc039c42690}, {{}, 0x0, {0xc000481f80, 0x4}, {0xc0368cb270, 0xe}, 0x0})
        net/http/transport.go:1780 +0x7e5 fp=0xc03f811ee0 sp=0xc03f811a28 pc=0x3886e5
net/http.(*Transport).dialConnFor(0xc0381824e0, 0xc029f780b0)
        net/http/transport.go:1615 +0xb8 fp=0xc03f811f90 sp=0xc03f811ee0 pc=0x3871f8
net/http.(*Transport).startDialConnForLocked.func1()
        net/http/transport.go:1597 +0x35 fp=0xc03f811fe0 sp=0xc03f811f90 pc=0x387035
runtime.goexit({})
        runtime/asm_amd64.s:1700 +0x1 fp=0xc03f811fe8 sp=0xc03f811fe0 pc=0x92361
created by net/http.(*Transport).startDialConnForLocked in goroutine 62160
        net/http/transport.go:1596 +0x112

goroutine 62464 gp=0xc03e438c40 m=nil [select, 2 minutes]:
runtime.gopark(0xc03f924190?, 0x2?, 0xd2?, 0x6f?, 0xc03f9240c4?)
        runtime/proc.go:435 +0xce fp=0xc03f923f50 sp=0xc03f923f30 pc=0x89fce
runtime.selectgo(0xc03f924190, 0xc03f9240c0, 0xe?, 0x0, 0x1888a?, 0x1)
        runtime/select.go:351 +0x837 fp=0xc03f924088 sp=0xc03f923f50 pc=0x69197
net/http.(*Transport).getConn(0xc03f8241a0, 0xc03ab10410, {{}, 0x0, {0xc000481f80, 0x4}, {0xc03d732450, 0xe}, 0x0})
        net/http/transport.go:1520 +0x4ae fp=0xc03f924260 sp=0xc03f924088 pc=0x3866ce
net/http.(*Transport).roundTrip(0xc03f8241a0, 0xc02e126b40)
        net/http/transport.go:685 +0xb57 fp=0xc03f924458 sp=0xc03f924260 pc=0x3823f7
net/http.(*Transport).RoundTrip(0x1dae918?, 0xc02623df10?)
        net/http/roundtrip.go:30 +0x13 fp=0xc03f924478 sp=0xc03f924458 pc=0x391733
go.k6.io/k6/lib/netext/httpext.(*transport).RoundTrip(0xc03dfe8780, 0xc02e126a00)
        go.k6.io/k6/lib/netext/httpext/transport.go:205 +0x474 fp=0xc03f924568 sp=0xc03f924478 pc=0xa533b4
net/http.send(0xc02e126a00, {0x1d9e1c0, 0xc03dfe8780}, {0xc03f924701?, 0x73e0c?, 0x0?})
        net/http/client.go:259 +0x5e2 fp=0xc03f924758 sp=0xc03f924568 pc=0x31dc02
net/http.(*Client).send(0xc03dfd1620, 0xc02e126a00, {0xc02f316010?, 0x27d91?, 0x0?})
        net/http/client.go:180 +0x91 fp=0xc03f9247d0 sp=0xc03f924758 pc=0x31d4b1
net/http.(*Client).do(0xc03dfd1620, 0xc02e126a00)
        net/http/client.go:728 +0x989 fp=0xc03f9249c0 sp=0xc03f9247d0 pc=0x31fac9
net/http.(*Client).Do(...)
        net/http/client.go:587
go.k6.io/k6/lib/netext/httpext.MakeRequest({0x1dae8a8, 0xc03ab10320}, 0xc03f842008, 0xc03dfdc360)
        go.k6.io/k6/lib/netext/httpext/request.go:265 +0x11c5 fp=0xc03f924d50 sp=0xc03f9249c0 pc=0xa4f465
go.k6.io/k6/js/modules/k6/http.(*Client).Request(0xc02f2a0c20, {0x19ed5d3, 0x3}, {0x1dc5968, 0xc000297430}, {0xc03f924e20, 0x1, 0x1})
        go.k6.io/k6/js/modules/k6/http/request.go:51 +0xfc fp=0xc03f924dc0 sp=0xc03f924d50 pc=0x11bb2dc
go.k6.io/k6/js/modules/k6/http.(*RootModule).NewModuleInstance.func2({0x1dc5968, 0xc000297430}, {0x2ef2c40?, 0x2?, 0x0?})
        go.k6.io/k6/js/modules/k6/http/http.go:75 +0x11e fp=0xc03f924e40 sp=0xc03f924dc0 pc=0x11ba5de
runtime.call64(0xc011cac210, 0xc02f2a0d40, 0x0, 0x0, 0x0, 0x28, 0xc03f9250c8)
        runtime/asm_amd64.s:777 +0x48 fp=0xc03f924e90 sp=0xc03f924e40 pc=0x909a8
runtime.reflectcall(0x1643040?, 0xc03ae4d950?, 0x8?, 0x1a0a0cc?, 0x0?, 0x12?, 0x1643040?)
        <autogenerated>:1 +0x36 fp=0xc03f924ed0 sp=0xc03f924e90 pc=0x97396
reflect.Value.call({0x170d080?, 0xc02f2a0d40?, 0xc03f925458?}, {0x19edf6b, 0x4}, {0xc03ae4d938, 0x1, 0xc03f925480?})
        reflect/value.go:584 +0xca6 fp=0xc03f925418 sp=0xc03f924ed0 pc=0x12a5a6
reflect.Value.Call({0x170d080?, 0xc02f2a0d40?, 0xc000297430?}, {0xc03ae4d938?, 0xc02e4c2ca0?, 0x0?})
        reflect/value.go:368 +0xb9 fp=0xc03f925490 sp=0xc03f925418 pc=0x1296b9
github.com/grafana/sobek.(*Runtime).newWrappedFunc.(*Runtime).wrapReflectFunc.func1({{0x1dc55d8, 0xc03f828fc0}, {0xc03dfaa4f0, 0x1, 0x5}})
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/runtime.go:2040 +0x3bd fp=0xc03f9255e8 sp=0xc03f925490 pc=0xd1cbfd
github.com/grafana/sobek.(*nativeFuncObject).vmCall(0xc03f80bbc0, 0xc03f80c120, 0x1)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/func.go:563 +0x183 fp=0xc03f925670 sp=0xc03f9255e8 pc=0xcdc223
github.com/grafana/sobek.call.exec(0x3?, 0xc03f80c120)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/vm.go:3732 +0x66 fp=0xc03f9256a0 sp=0xc03f925670 pc=0xd52b26
github.com/grafana/sobek.(*call).exec(0x800000001dc55d8?, 0xc03f80c120?)
        <autogenerated>:1 +0x25 fp=0xc03f9256c0 sp=0xc03f9256a0 pc=0xdaa1c5
github.com/grafana/sobek.(*vm).run(0xc03f80c120)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/vm.go:642 +0x5b fp=0xc03f925710 sp=0xc03f9256c0 pc=0xd3d47b
github.com/grafana/sobek.(*vm).runTryInner(0xc03f80c120?)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/vm.go:893 +0x52 fp=0xc03f925758 sp=0xc03f925710 pc=0xd3ee72
github.com/grafana/sobek.(*baseJsFuncObject).__call(0xc03f80b980, {0xc02e4c2c80?, 0x1, 0x480?}, {0x0, 0x0}, {0x1dc5bc8?, 0x2ef2c40?})
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/func.go:426 +0x705 fp=0xc03f925868 sp=0xc03f925758 pc=0xcdb145
github.com/grafana/sobek.(*baseJsFuncObject)._call(...)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/func.go:442
github.com/grafana/sobek.(*baseJsFuncObject).call(0x1fe63eebf90?, {{0x1dc5bc8, 0x2ef2c40}, {0xc02e4c2c80, 0x1, 0x1}}, {0x0?, 0x0?})
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/func.go:450 +0x76 fp=0xc03f9258b8 sp=0xc03f925868 pc=0xcdb556
github.com/grafana/sobek.(*baseJsFuncObject).Call(...)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/func.go:382
github.com/grafana/sobek.(*baseJsFuncObject).Call-fm({{0x1dc5bc8, 0x2ef2c40}, {0xc02e4c2c80, 0x1, 0x1}})
        <autogenerated>:1 +0x90 fp=0xc03f925930 sp=0xc03f9258b8 pc=0xd80850
github.com/grafana/sobek.AssertFunction.func1.1()
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/runtime.go:2481 +0x56 fp=0xc03f925998 sp=0xc03f925930 pc=0xd26096
github.com/grafana/sobek.(*vm).try(0xc03f80c120, 0xc03f925af0)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/vm.go:870 +0x23c fp=0xc03f925a78 sp=0xc03f925998 pc=0xd3e9fc
github.com/grafana/sobek.(*Runtime).runWrapped(0xc03e451408, 0x87679?)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/runtime.go:2525 +0x5f fp=0xc03f925ad0 sp=0xc03f925a78 pc=0xd2637f
github.com/grafana/sobek.AssertFunction.func1({0x1dc5bc8?, 0x2ef2c40?}, {0xc02e4c2c80?, 0x1?, 0x1?})
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/runtime.go:2480 +0x8c fp=0xc03f925b40 sp=0xc03f925ad0 pc=0xd25fcc
go.k6.io/k6/internal/js.(*VU).runFn.func2()
        go.k6.io/k6/internal/js/runner.go:915 +0x3e fp=0xc03f925b80 sp=0xc03f925b40 pc=0x1495d7e
go.k6.io/k6/internal/js/eventloop.(*EventLoop).Start(0xc03b460a50, 0xc03dfd14d0)
        go.k6.io/k6/internal/js/eventloop/eventloop.go:177 +0x197 fp=0xc03f925c68 sp=0xc03f925b80 pc=0xdcdf57
go.k6.io/k6/internal/js.(*VU).runFn(0xc04039e000, {0x1dae8a8, 0xc03ab10320}, 0x1, 0xc03ae4d890, 0xc02e4c2c60, {0xc02e4c2c80, 0x1, 0x1})
        go.k6.io/k6/internal/js/runner.go:914 +0x269 fp=0xc03f925d68 sp=0xc03f925c68 pc=0x14958c9
go.k6.io/k6/internal/js.(*ActiveVU).RunOnce(0xc03ef290c0)
        go.k6.io/k6/internal/js/runner.go:847 +0x48f fp=0xc03f925ee0 sp=0xc03f925d68 pc=0x149518f
go.k6.io/k6/lib/executor.RampingArrivalRate.Run.getIterationRunner.func8({0x1dae870, 0xc0119da030}, {0x1d98080?, 0xc03ef290c0?})
        go.k6.io/k6/lib/executor/helpers.go:108 +0x4a fp=0xc03f925f58 sp=0xc03f925ee0 pc=0x70752a
go.k6.io/k6/lib/executor.(*activeVUPool).AddVU.func1()
        go.k6.io/k6/lib/executor/ramping_arrival_rate.go:546 +0xd5 fp=0xc03f925fe0 sp=0xc03f925f58 pc=0x707f75
runtime.goexit({})
        runtime/asm_amd64.s:1700 +0x1 fp=0xc03f925fe8 sp=0xc03f925fe0 pc=0x92361
created by go.k6.io/k6/lib/executor.(*activeVUPool).AddVU in goroutine 1235
        go.k6.io/k6/lib/executor/ramping_arrival_rate.go:539 +0xef

goroutine 62320 gp=0xc039828000 m=nil [runnable]:
runtime.cgocall(0x93b80, 0xc03e517b48)
        runtime/cgocall.go:167 +0x3e fp=0xc03f929038 sp=0xc03f928fd0 pc=0x86b3e
runtime.syscall_syscalln(0x22c8c0?, 0xc02cfc95d0?, {0xc03f929080?, 0x0?, 0x0?})
        runtime/syscall_windows.go:521 +0x4e fp=0xc03f929058 sp=0xc03f929038 pc=0x73a2e
syscall.Syscall(0xc03f929180?, 0x1fe636a4d08?, 0xc03f9290d8?, 0x89005?, 0x2ef37a0?)
        runtime/syscall_windows.go:457 +0x29 fp=0xc03f9290a8 sp=0xc03f929058 pc=0x8dec9
syscall.Closesocket(0x1d3cc)
        syscall/zsyscall_windows.go:1342 +0x4f fp=0xc03f9290e8 sp=0xc03f9290a8 pc=0xb6def
internal/poll.(*FD).destroy(0xc038843b88)
        internal/poll/fd_windows.go:372 +0x63 fp=0xc03f929110 sp=0xc03f9290e8 pc=0xf1023
internal/poll.(*FD).decref(0x1fe636a4cd8?)
        internal/poll/fd_mutex.go:213 +0x53 fp=0xc03f929130 sp=0xc03f929110 pc=0xeefd3
internal/poll.(*FD).Close(0xc038843b88)
        internal/poll/fd_windows.go:392 +0x65 fp=0xc03f929160 sp=0xc03f929130 pc=0xf1105
net.(*netFD).Close(0xc038843b88)
        net/fd_posix.go:37 +0x32 fp=0xc03f929190 sp=0xc03f929160 pc=0x22aa32
net.socket({0x1dae918, 0xc029250fc0}, {0x19ed61e, 0x3}, 0x2, 0x1, 0xc03f9292e8?, 0x0, {0x1db5df8, 0x0}, ...)
        net/sock_posix.go:71 +0x2c8 fp=0xc03f929238 sp=0xc03f929190 pc=0x2443a8
net.internetSocket({0x1dae918, 0xc029250fc0}, {0x19ed61e, 0x3}, {0x1db5df8, 0x0}, {0x1db5df8?, 0xc039809b60?}, 0x1, 0x0, ...)
        net/ipsock_posix.go:167 +0x1e5 fp=0xc03f9292c0 sp=0xc03f929238 pc=0x235005
net.(*sysDialer).doDialTCPProto(0xc039806900, {0x1dae918, 0xc029250fc0}, 0x0, 0xc039809b60, 0x0)
        net/tcpsock_posix.go:85 +0xe7 fp=0xc03f929370 sp=0xc03f9292c0 pc=0x247ea7
net.(*sysDialer).doDialTCP(...)
        net/tcpsock_posix.go:75
net.(*sysDialer).dialTCP(0xc039809b60?, {0x1dae918?, 0xc029250fc0?}, 0x166dd20?, 0xc03f929448?)
        net/tcpsock_posix.go:71 +0x69 fp=0xc03f9293b0 sp=0xc03f929370 pc=0x247d49
net.(*sysDialer).dialSingle(0xc039806900, {0x1dae918, 0xc029250fc0}, {0x1da5628, 0xc039809b60})
        net/dial.go:721 +0x3ce fp=0xc03f929480 sp=0xc03f9293b0 pc=0x2224ae
net.(*sysDialer).dialSerial(0xc039806900, {0x1dae918, 0xc029250fc0}, {0xc02cfc95b0?, 0x1, 0xc039809b30?})
        net/dial.go:686 +0x24e fp=0xc03f929588 sp=0xc03f929480 pc=0x221c8e
net.(*sysDialer).dialParallel(0x0?, {0x1dae918?, 0xc029250fc0?}, {0xc02cfc95b0?, 0x1747280?, 0x19edf53?}, {0x0?, 0x19ed61e?, 0xc0343c9620?})
        net/dial.go:587 +0x3a7 fp=0xc03f9297a0 sp=0xc03f929588 pc=0x221367
net.(*Dialer).DialContext(0xc03ef56620, {0x1dae8a8, 0xc034a935e0}, {0x19ed61e, 0x3}, {0xc0343c9630, 0xe})
        net/dial.go:578 +0x6ac fp=0xc03f929910 sp=0xc03f9297a0 pc=0x220bac
go.k6.io/k6/lib/netext.(*Dialer).DialContext(0xc03ef56620, {0x1dae8a8, 0xc034a935e0}, {0x19ed61e, 0x3}, {0xc0343c9600?, 0xd01f8?})
        go.k6.io/k6/lib/netext/dialer.go:64 +0x7d fp=0xc03f929978 sp=0xc03f929910 pc=0xa432fd
go.k6.io/k6/lib/netext.(*Dialer).DialContext-fm({0x1dae8a8?, 0xc034a935e0?}, {0x19ed61e?, 0xc039809920?}, {0xc0343c9600?, 0xc02ab79a18?})
        <autogenerated>:1 +0x49 fp=0xc03f9299c0 sp=0xc03f929978 pc=0x1498529
net/http.(*Transport).dial(0x0?, {0x1dae8a8?, 0xc034a935e0?}, {0x19ed61e?, 0xfffffffffffffffe?}, {0xc0343c9600?, 0xc02ab79a10?})
        net/http/transport.go:1278 +0xd2 fp=0xc03f929a28 sp=0xc03f9299c0 pc=0x385712
net/http.(*Transport).dialConn(0xc039289d40, {0x1dae8a8, 0xc034a935e0}, {{}, 0x0, {0xc000481f80, 0x4}, {0xc0343c9600, 0xe}, 0x0})
        net/http/transport.go:1780 +0x7e5 fp=0xc03f929ee0 sp=0xc03f929a28 pc=0x3886e5
net/http.(*Transport).dialConnFor(0xc039289d40, 0xc0200982c0)
        net/http/transport.go:1615 +0xb8 fp=0xc03f929f90 sp=0xc03f929ee0 pc=0x3871f8
net/http.(*Transport).startDialConnForLocked.func1()
        net/http/transport.go:1597 +0x35 fp=0xc03f929fe0 sp=0xc03f929f90 pc=0x387035
runtime.goexit({})
        runtime/asm_amd64.s:1700 +0x1 fp=0xc03f929fe8 sp=0xc03f929fe0 pc=0x92361
created by net/http.(*Transport).startDialConnForLocked in goroutine 62462
        net/http/transport.go:1596 +0x112

goroutine 62599 gp=0xc03d0daa80 m=nil [select, 2 minutes]:
runtime.gopark(0xc03fa02190?, 0x2?, 0xd2?, 0x6f?, 0xc03fa020c4?)
        runtime/proc.go:435 +0xce fp=0xc03fa01f50 sp=0xc03fa01f30 pc=0x89fce
runtime.selectgo(0xc03fa02190, 0xc03fa020c0, 0xe?, 0x0, 0x1888a?, 0x1)
        runtime/select.go:351 +0x837 fp=0xc03fa02088 sp=0xc03fa01f50 pc=0x69197
net/http.(*Transport).getConn(0xc03f2604e0, 0xc03ac98c80, {{}, 0x0, {0xc000481f80, 0x4}, {0xc035e37ef0, 0xe}, 0x0})
        net/http/transport.go:1520 +0x4ae fp=0xc03fa02260 sp=0xc03fa02088 pc=0x3866ce
net/http.(*Transport).roundTrip(0xc03f2604e0, 0xc02e0a68c0)
        net/http/transport.go:685 +0xb57 fp=0xc03fa02458 sp=0xc03fa02260 pc=0x3823f7
net/http.(*Transport).RoundTrip(0x1dae918?, 0xc02841bb20?)
        net/http/roundtrip.go:30 +0x13 fp=0xc03fa02478 sp=0xc03fa02458 pc=0x391733
go.k6.io/k6/lib/netext/httpext.(*transport).RoundTrip(0xc03ca82a40, 0xc02e0a6780)
        go.k6.io/k6/lib/netext/httpext/transport.go:205 +0x474 fp=0xc03fa02568 sp=0xc03fa02478 pc=0xa533b4
net/http.send(0xc02e0a6780, {0x1d9e1c0, 0xc03ca82a40}, {0xc03fa02701?, 0x73e0c?, 0x0?})
        net/http/client.go:259 +0x5e2 fp=0xc03fa02758 sp=0xc03fa02568 pc=0x31dc02
net/http.(*Client).send(0xc03fa90ea0, 0xc02e0a6780, {0xc02841bba0?, 0x27d91?, 0x0?})
        net/http/client.go:180 +0x91 fp=0xc03fa027d0 sp=0xc03fa02758 pc=0x31d4b1
net/http.(*Client).do(0xc03fa90ea0, 0xc02e0a6780)
        net/http/client.go:728 +0x989 fp=0xc03fa029c0 sp=0xc03fa027d0 pc=0x31fac9
net/http.(*Client).Do(...)
        net/http/client.go:587
go.k6.io/k6/lib/netext/httpext.MakeRequest({0x1dae8a8, 0xc03ac98b90}, 0xc03a82d508, 0xc03fa963f0)
        go.k6.io/k6/lib/netext/httpext/request.go:265 +0x11c5 fp=0xc03fa02d50 sp=0xc03fa029c0 pc=0xa4f465
go.k6.io/k6/js/modules/k6/http.(*Client).Request(0xc02ee374f0, {0x19ed5d3, 0x3}, {0x1dc5968, 0xc000297430}, {0xc03fa02e20, 0x1, 0x1})
        go.k6.io/k6/js/modules/k6/http/request.go:51 +0xfc fp=0xc03fa02dc0 sp=0xc03fa02d50 pc=0x11bb2dc
go.k6.io/k6/js/modules/k6/http.(*RootModule).NewModuleInstance.func2({0x1dc5968, 0xc000297430}, {0x2ef2c40?, 0x2?, 0x0?})
        go.k6.io/k6/js/modules/k6/http/http.go:75 +0x11e fp=0xc03fa02e40 sp=0xc03fa02dc0 pc=0x11ba5de
runtime.call64(0xc011cac210, 0xc02ee375d0, 0x0, 0x0, 0x0, 0x28, 0xc03fa030c8)
        runtime/asm_amd64.s:777 +0x48 fp=0xc03fa02e90 sp=0xc03fa02e40 pc=0x909a8
runtime.reflectcall(0x1643040?, 0xc03673a720?, 0x8?, 0x1a0a0cc?, 0x0?, 0x12?, 0x1643040?)
        <autogenerated>:1 +0x36 fp=0xc03fa02ed0 sp=0xc03fa02e90 pc=0x97396
reflect.Value.call({0x170d080?, 0xc02ee375d0?, 0xc03fa03458?}, {0x19edf6b, 0x4}, {0xc03673a6d8, 0x1, 0xc03fa03480?})
        reflect/value.go:584 +0xca6 fp=0xc03fa03418 sp=0xc03fa02ed0 pc=0x12a5a6
reflect.Value.Call({0x170d080?, 0xc02ee375d0?, 0xc000297430?}, {0xc03673a6d8?, 0xc02edbc5d0?, 0xc01453d0a0?})
        reflect/value.go:368 +0xb9 fp=0xc03fa03490 sp=0xc03fa03418 pc=0x1296b9
github.com/grafana/sobek.(*Runtime).newWrappedFunc.(*Runtime).wrapReflectFunc.func1({{0x1dc55d8, 0xc03f35e660}, {0xc03fa88970, 0x1, 0x5}})
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/runtime.go:2040 +0x3bd fp=0xc03fa035e8 sp=0xc03fa03490 pc=0xd1cbfd
github.com/grafana/sobek.(*nativeFuncObject).vmCall(0xc03f34ea80, 0xc03f304480, 0x1)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/func.go:563 +0x183 fp=0xc03fa03670 sp=0xc03fa035e8 pc=0xcdc223
github.com/grafana/sobek.call.exec(0x3?, 0xc03f304480)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/vm.go:3732 +0x66 fp=0xc03fa036a0 sp=0xc03fa03670 pc=0xd52b26
github.com/grafana/sobek.(*call).exec(0x800000000000004?, 0xc03f304480?)
        <autogenerated>:1 +0x25 fp=0xc03fa036c0 sp=0xc03fa036a0 pc=0xdaa1c5
github.com/grafana/sobek.(*vm).run(0xc03f304480)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/vm.go:642 +0x5b fp=0xc03fa03710 sp=0xc03fa036c0 pc=0xd3d47b
github.com/grafana/sobek.(*vm).runTryInner(0xc03f304480?)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/vm.go:893 +0x52 fp=0xc03fa03758 sp=0xc03fa03710 pc=0xd3ee72
github.com/grafana/sobek.(*baseJsFuncObject).__call(0xc03f34e840, {0xc02edbc5b0?, 0x1, 0x480?}, {0x0, 0x0}, {0x1dc5bc8?, 0x2ef2c40?})
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/func.go:426 +0x705 fp=0xc03fa03868 sp=0xc03fa03758 pc=0xcdb145
github.com/grafana/sobek.(*baseJsFuncObject)._call(...)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/func.go:442
github.com/grafana/sobek.(*baseJsFuncObject).call(0x1fe64df7628?, {{0x1dc5bc8, 0x2ef2c40}, {0xc02edbc5b0, 0x1, 0x1}}, {0x0?, 0x0?})
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/func.go:450 +0x76 fp=0xc03fa038b8 sp=0xc03fa03868 pc=0xcdb556
github.com/grafana/sobek.(*baseJsFuncObject).Call(...)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/func.go:382
github.com/grafana/sobek.(*baseJsFuncObject).Call-fm({{0x1dc5bc8, 0x2ef2c40}, {0xc02edbc5b0, 0x1, 0x1}})
        <autogenerated>:1 +0x90 fp=0xc03fa03930 sp=0xc03fa038b8 pc=0xd80850
github.com/grafana/sobek.AssertFunction.func1.1()
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/runtime.go:2481 +0x56 fp=0xc03fa03998 sp=0xc03fa03930 pc=0xd26096
github.com/grafana/sobek.(*vm).try(0xc03f304480, 0xc03fa03af0)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/vm.go:870 +0x23c fp=0xc03fa03a78 sp=0xc03fa03998 pc=0xd3e9fc
github.com/grafana/sobek.(*Runtime).runWrapped(0xc03dbef808, 0x87679?)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/runtime.go:2525 +0x5f fp=0xc03fa03ad0 sp=0xc03fa03a78 pc=0xd2637f
github.com/grafana/sobek.AssertFunction.func1({0x1dc5bc8?, 0x2ef2c40?}, {0xc02edbc5b0?, 0x1?, 0x1?})
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/runtime.go:2480 +0x8c fp=0xc03fa03b40 sp=0xc03fa03ad0 pc=0xd25fcc
go.k6.io/k6/internal/js.(*VU).runFn.func2()
        go.k6.io/k6/internal/js/runner.go:915 +0x3e fp=0xc03fa03b80 sp=0xc03fa03b40 pc=0x1495d7e
go.k6.io/k6/internal/js/eventloop.(*EventLoop).Start(0xc03af27900, 0xc03fa90d50)
        go.k6.io/k6/internal/js/eventloop/eventloop.go:177 +0x197 fp=0xc03fa03c68 sp=0xc03fa03b80 pc=0xdcdf57
go.k6.io/k6/internal/js.(*VU).runFn(0xc040846280, {0x1dae8a8, 0xc03ac98b90}, 0x1, 0xc03673a690, 0xc02edbc590, {0xc02edbc5b0, 0x1, 0x1})
        go.k6.io/k6/internal/js/runner.go:914 +0x269 fp=0xc03fa03d68 sp=0xc03fa03c68 pc=0x14958c9
go.k6.io/k6/internal/js.(*ActiveVU).RunOnce(0xc03f203580)
        go.k6.io/k6/internal/js/runner.go:847 +0x48f fp=0xc03fa03ee0 sp=0xc03fa03d68 pc=0x149518f
go.k6.io/k6/lib/executor.RampingArrivalRate.Run.getIterationRunner.func8({0x1dae870, 0xc0119da030}, {0x1d98080?, 0xc03f203580?})
        go.k6.io/k6/lib/executor/helpers.go:108 +0x4a fp=0xc03fa03f58 sp=0xc03fa03ee0 pc=0x70752a
go.k6.io/k6/lib/executor.(*activeVUPool).AddVU.func1()
        go.k6.io/k6/lib/executor/ramping_arrival_rate.go:546 +0xd5 fp=0xc03fa03fe0 sp=0xc03fa03f58 pc=0x707f75
runtime.goexit({})
        runtime/asm_amd64.s:1700 +0x1 fp=0xc03fa03fe8 sp=0xc03fa03fe0 pc=0x92361
created by go.k6.io/k6/lib/executor.(*activeVUPool).AddVU in goroutine 1235
        go.k6.io/k6/lib/executor/ramping_arrival_rate.go:539 +0xef

goroutine 62643 gp=0xc03d0dac40 m=nil [select, 2 minutes]:
runtime.gopark(0xc03f75c190?, 0x2?, 0xd2?, 0x6f?, 0xc03f75c0c4?)
        runtime/proc.go:435 +0xce fp=0xc03f75bf50 sp=0xc03f75bf30 pc=0x89fce
runtime.selectgo(0xc03f75c190, 0xc03f75c0c0, 0xe?, 0x0, 0x1888a?, 0x1)
        runtime/select.go:351 +0x837 fp=0xc03f75c088 sp=0xc03f75bf50 pc=0x69197
net/http.(*Transport).getConn(0xc03e0b2340, 0xc03b078ff0, {{}, 0x0, {0xc000481f80, 0x4}, {0xc036871ad0, 0xe}, 0x0})
        net/http/transport.go:1520 +0x4ae fp=0xc03f75c260 sp=0xc03f75c088 pc=0x3866ce
net/http.(*Transport).roundTrip(0xc03e0b2340, 0xc02dfafa40)
        net/http/transport.go:685 +0xb57 fp=0xc03f75c458 sp=0xc03f75c260 pc=0x3823f7
net/http.(*Transport).RoundTrip(0x1dae918?, 0xc02a804540?)
        net/http/roundtrip.go:30 +0x13 fp=0xc03f75c478 sp=0xc03f75c458 pc=0x391733
go.k6.io/k6/lib/netext/httpext.(*transport).RoundTrip(0xc03e9b9f40, 0xc02dfaf900)
        go.k6.io/k6/lib/netext/httpext/transport.go:205 +0x474 fp=0xc03f75c568 sp=0xc03f75c478 pc=0xa533b4
net/http.send(0xc02dfaf900, {0x1d9e1c0, 0xc03e9b9f40}, {0xc03f75c701?, 0x73e0c?, 0x0?})
        net/http/client.go:259 +0x5e2 fp=0xc03f75c758 sp=0xc03f75c568 pc=0x31dc02
net/http.(*Client).send(0xc03f72daa0, 0xc02dfaf900, {0xc02a8046a0?, 0x27d91?, 0x0?})
        net/http/client.go:180 +0x91 fp=0xc03f75c7d0 sp=0xc03f75c758 pc=0x31d4b1
net/http.(*Client).do(0xc03f72daa0, 0xc02dfaf900)
        net/http/client.go:728 +0x989 fp=0xc03f75c9c0 sp=0xc03f75c7d0 pc=0x31fac9
net/http.(*Client).Do(...)
        net/http/client.go:587
go.k6.io/k6/lib/netext/httpext.MakeRequest({0x1dae8a8, 0xc03b078f00}, 0xc03e0b6388, 0xc03ea7f830)
        go.k6.io/k6/lib/netext/httpext/request.go:265 +0x11c5 fp=0xc03f75cd50 sp=0xc03f75c9c0 pc=0xa4f465
go.k6.io/k6/js/modules/k6/http.(*Client).Request(0xc02e998d90, {0x19ed5d3, 0x3}, {0x1dc5968, 0xc000297430}, {0xc03f75ce20, 0x1, 0x1})
        go.k6.io/k6/js/modules/k6/http/request.go:51 +0xfc fp=0xc03f75cdc0 sp=0xc03f75cd50 pc=0x11bb2dc
go.k6.io/k6/js/modules/k6/http.(*RootModule).NewModuleInstance.func2({0x1dc5968, 0xc000297430}, {0x2ef2c40?, 0x2?, 0x0?})
        go.k6.io/k6/js/modules/k6/http/http.go:75 +0x11e fp=0xc03f75ce40 sp=0xc03f75cdc0 pc=0x11ba5de
runtime.call64(0xc011cac210, 0xc02e998e70, 0x0, 0x0, 0x0, 0x28, 0xc03f75d0c8)
        runtime/asm_amd64.s:777 +0x48 fp=0xc03f75ce90 sp=0xc03f75ce40 pc=0x909a8
runtime.reflectcall(0x1643040?, 0xc03f9bc438?, 0x8?, 0x1a0a0cc?, 0x0?, 0x12?, 0x1643040?)
        <autogenerated>:1 +0x36 fp=0xc03f75ced0 sp=0xc03f75ce90 pc=0x97396
reflect.Value.call({0x170d080?, 0xc02e998e70?, 0xc03f75d458?}, {0x19edf6b, 0x4}, {0xc03f9bc3a8, 0x1, 0xc03f75d480?})
        reflect/value.go:584 +0xca6 fp=0xc03f75d418 sp=0xc03f75ced0 pc=0x12a5a6
reflect.Value.Call({0x170d080?, 0xc02e998e70?, 0xc000297430?}, {0xc03f9bc3a8?, 0xc02f409bb0?, 0xc014841530?})
        reflect/value.go:368 +0xb9 fp=0xc03f75d490 sp=0xc03f75d418 pc=0x1296b9
github.com/grafana/sobek.(*Runtime).newWrappedFunc.(*Runtime).wrapReflectFunc.func1({{0x1dc55d8, 0xc03f91ade0}, {0xc03f732c70, 0x1, 0x5}})
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/runtime.go:2040 +0x3bd fp=0xc03f75d5e8 sp=0xc03f75d490 pc=0xd1cbfd
github.com/grafana/sobek.(*nativeFuncObject).vmCall(0xc03e0adc80, 0xc03e099d40, 0x1)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/func.go:563 +0x183 fp=0xc03f75d670 sp=0xc03f75d5e8 pc=0xcdc223
github.com/grafana/sobek.call.exec(0x3?, 0xc03e099d40)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/vm.go:3732 +0x66 fp=0xc03f75d6a0 sp=0xc03f75d670 pc=0xd52b26
github.com/grafana/sobek.(*call).exec(0x800000000000003?, 0xc03e099d40?)
        <autogenerated>:1 +0x25 fp=0xc03f75d6c0 sp=0xc03f75d6a0 pc=0xdaa1c5
github.com/grafana/sobek.(*vm).run(0xc03e099d40)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/vm.go:642 +0x5b fp=0xc03f75d710 sp=0xc03f75d6c0 pc=0xd3d47b
github.com/grafana/sobek.(*vm).runTryInner(0xc03e099d40?)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/vm.go:893 +0x52 fp=0xc03f75d758 sp=0xc03f75d710 pc=0xd3ee72
github.com/grafana/sobek.(*baseJsFuncObject).__call(0xc03e0ada40, {0xc02f409b90?, 0x1, 0x480?}, {0x0, 0x0}, {0x1dc5bc8?, 0x2ef2c40?})
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/func.go:426 +0x705 fp=0xc03f75d868 sp=0xc03f75d758 pc=0xcdb145
github.com/grafana/sobek.(*baseJsFuncObject)._call(...)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/func.go:442
github.com/grafana/sobek.(*baseJsFuncObject).call(0x1fe643d6568?, {{0x1dc5bc8, 0x2ef2c40}, {0xc02f409b90, 0x1, 0x1}}, {0x0?, 0x0?})
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/func.go:450 +0x76 fp=0xc03f75d8b8 sp=0xc03f75d868 pc=0xcdb556
github.com/grafana/sobek.(*baseJsFuncObject).Call(...)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/func.go:382
github.com/grafana/sobek.(*baseJsFuncObject).Call-fm({{0x1dc5bc8, 0x2ef2c40}, {0xc02f409b90, 0x1, 0x1}})
        <autogenerated>:1 +0x90 fp=0xc03f75d930 sp=0xc03f75d8b8 pc=0xd80850
github.com/grafana/sobek.AssertFunction.func1.1()
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/runtime.go:2481 +0x56 fp=0xc03f75d998 sp=0xc03f75d930 pc=0xd26096
github.com/grafana/sobek.(*vm).try(0xc03e099d40, 0xc014841af0)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/vm.go:870 +0x23c fp=0xc03f75da78 sp=0xc03f75d998 pc=0xd3e9fc
github.com/grafana/sobek.(*Runtime).runWrapped(0xc03cfbbc08, 0x87679?)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/runtime.go:2525 +0x5f fp=0xc03f75dad0 sp=0xc03f75da78 pc=0xd2637f
github.com/grafana/sobek.AssertFunction.func1({0x1dc5bc8?, 0x2ef2c40?}, {0xc02f409b90?, 0x1?, 0x1?})
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/runtime.go:2480 +0x8c fp=0xc03f75db40 sp=0xc03f75dad0 pc=0xd25fcc
go.k6.io/k6/internal/js.(*VU).runFn.func2()
        go.k6.io/k6/internal/js/runner.go:915 +0x3e fp=0xc03f75db80 sp=0xc03f75db40 pc=0x1495d7e
go.k6.io/k6/internal/js/eventloop.(*EventLoop).Start(0xc03a227b30, 0xc03f72d950)
        go.k6.io/k6/internal/js/eventloop/eventloop.go:177 +0x197 fp=0xc03f75dc68 sp=0xc03f75db80 pc=0xdcdf57
go.k6.io/k6/internal/js.(*VU).runFn(0xc03fef9220, {0x1dae8a8, 0xc03b078f00}, 0x1, 0xc03f9bc390, 0xc02f409b70, {0xc02f409b90, 0x1, 0x1})
        go.k6.io/k6/internal/js/runner.go:914 +0x269 fp=0xc03f75dd68 sp=0xc03f75dc68 pc=0x14958c9
go.k6.io/k6/internal/js.(*ActiveVU).RunOnce(0xc03e1cf6c0)
        go.k6.io/k6/internal/js/runner.go:847 +0x48f fp=0xc03f75dee0 sp=0xc03f75dd68 pc=0x149518f
go.k6.io/k6/lib/executor.RampingArrivalRate.Run.getIterationRunner.func8({0x1dae870, 0xc0119da030}, {0x1d98080?, 0xc03e1cf6c0?})
        go.k6.io/k6/lib/executor/helpers.go:108 +0x4a fp=0xc03f75df58 sp=0xc03f75dee0 pc=0x70752a
go.k6.io/k6/lib/executor.(*activeVUPool).AddVU.func1()
        go.k6.io/k6/lib/executor/ramping_arrival_rate.go:546 +0xd5 fp=0xc03f75dfe0 sp=0xc03f75df58 pc=0x707f75
runtime.goexit({})
        runtime/asm_amd64.s:1700 +0x1 fp=0xc03f75dfe8 sp=0xc03f75dfe0 pc=0x92361
created by go.k6.io/k6/lib/executor.(*activeVUPool).AddVU in goroutine 1235
        go.k6.io/k6/lib/executor/ramping_arrival_rate.go:539 +0xef

goroutine 62538 gp=0xc03ea3c700 m=nil [select, 2 minutes]:
runtime.gopark(0xc03f760190?, 0x2?, 0xd2?, 0x6f?, 0xc03f7600c4?)
        runtime/proc.go:435 +0xce fp=0xc03f75ff50 sp=0xc03f75ff30 pc=0x89fce
runtime.selectgo(0xc03f760190, 0xc03f7600c0, 0xe?, 0x0, 0x1888a?, 0x1)
        runtime/select.go:351 +0x837 fp=0xc03f760088 sp=0xc03f75ff50 pc=0x69197
net/http.(*Transport).getConn(0xc03d5cb1e0, 0xc03a6b8550, {{}, 0x0, {0xc000481f80, 0x4}, {0xc038040d90, 0xe}, 0x0})
        net/http/transport.go:1520 +0x4ae fp=0xc03f760260 sp=0xc03f760088 pc=0x3866ce
net/http.(*Transport).roundTrip(0xc03d5cb1e0, 0xc02cf95540)
        net/http/transport.go:685 +0xb57 fp=0xc03f760458 sp=0xc03f760260 pc=0x3823f7
net/http.(*Transport).RoundTrip(0x1dae918?, 0xc023700fc0?)
        net/http/roundtrip.go:30 +0x13 fp=0xc03f760478 sp=0xc03f760458 pc=0x391733
go.k6.io/k6/lib/netext/httpext.(*transport).RoundTrip(0xc038b87180, 0xc02cf95400)
        go.k6.io/k6/lib/netext/httpext/transport.go:205 +0x474 fp=0xc03f760568 sp=0xc03f760478 pc=0xa533b4
net/http.send(0xc02cf95400, {0x1d9e1c0, 0xc038b87180}, {0xc03f760701?, 0x73e0c?, 0x0?})
        net/http/client.go:259 +0x5e2 fp=0xc03f760758 sp=0xc03f760568 pc=0x31dc02
net/http.(*Client).send(0xc038bc04b0, 0xc02cf95400, {0xc023701120?, 0x27d91?, 0x0?})
        net/http/client.go:180 +0x91 fp=0xc03f7607d0 sp=0xc03f760758 pc=0x31d4b1
net/http.(*Client).do(0xc038bc04b0, 0xc02cf95400)
        net/http/client.go:728 +0x989 fp=0xc03f7609c0 sp=0xc03f7607d0 pc=0x31fac9
net/http.(*Client).Do(...)
        net/http/client.go:587
go.k6.io/k6/lib/netext/httpext.MakeRequest({0x1dae8a8, 0xc03a6b8410}, 0xc03e9cea88, 0xc038b9d5f0)
        go.k6.io/k6/lib/netext/httpext/request.go:265 +0x11c5 fp=0xc03f760d50 sp=0xc03f7609c0 pc=0xa4f465
go.k6.io/k6/js/modules/k6/http.(*Client).Request(0xc02f409260, {0x19ed5d3, 0x3}, {0x1dc5968, 0xc000297430}, {0xc03f760e20, 0x1, 0x1})
        go.k6.io/k6/js/modules/k6/http/request.go:51 +0xfc fp=0xc03f760dc0 sp=0xc03f760d50 pc=0x11bb2dc
go.k6.io/k6/js/modules/k6/http.(*RootModule).NewModuleInstance.func2({0x1dc5968, 0xc000297430}, {0x2ef2c40?, 0x2?, 0x0?})
        go.k6.io/k6/js/modules/k6/http/http.go:75 +0x11e fp=0xc03f760e40 sp=0xc03f760dc0 pc=0x11ba5de
runtime.call64(0xc011cac210, 0xc02f409340, 0x0, 0x0, 0x0, 0x28, 0xc03f7610c8)
        runtime/asm_amd64.s:777 +0x48 fp=0xc03f760e90 sp=0xc03f760e40 pc=0x909a8
runtime.reflectcall(0x1643040?, 0xc030740108?, 0x8?, 0x1a0a0cc?, 0x0?, 0x12?, 0x1643040?)
        <autogenerated>:1 +0x36 fp=0xc03f760ed0 sp=0xc03f760e90 pc=0x97396
reflect.Value.call({0x170d080?, 0xc02f409340?, 0xc03f761458?}, {0x19edf6b, 0x4}, {0xc0307400f0, 0x1, 0xc03f761480?})
        reflect/value.go:584 +0xca6 fp=0xc03f761418 sp=0xc03f760ed0 pc=0x12a5a6
reflect.Value.Call({0x170d080?, 0xc02f409340?, 0xc000297430?}, {0xc0307400f0?, 0xc02d995b00?, 0xc0405dcc30?})
        reflect/value.go:368 +0xb9 fp=0xc03f761490 sp=0xc03f761418 pc=0x1296b9
github.com/grafana/sobek.(*Runtime).newWrappedFunc.(*Runtime).wrapReflectFunc.func1({{0x1dc55d8, 0xc03f7277d0}, {0xc038baaf70, 0x1, 0x5}})
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/runtime.go:2040 +0x3bd fp=0xc03f7615e8 sp=0xc03f761490 pc=0xd1cbfd
github.com/grafana/sobek.(*nativeFuncObject).vmCall(0xc03ea7bec0, 0xc03ea779e0, 0x1)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/func.go:563 +0x183 fp=0xc03f761670 sp=0xc03f7615e8 pc=0xcdc223
github.com/grafana/sobek.call.exec(0x3?, 0xc03ea779e0)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/vm.go:3732 +0x66 fp=0xc03f7616a0 sp=0xc03f761670 pc=0xd52b26
github.com/grafana/sobek.(*call).exec(0x800000001dc55d8?, 0xc03ea779e0?)
        <autogenerated>:1 +0x25 fp=0xc03f7616c0 sp=0xc03f7616a0 pc=0xdaa1c5
github.com/grafana/sobek.(*vm).run(0xc03ea779e0)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/vm.go:642 +0x5b fp=0xc03f761710 sp=0xc03f7616c0 pc=0xd3d47b
github.com/grafana/sobek.(*vm).runTryInner(0xc03ea779e0?)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/vm.go:893 +0x52 fp=0xc03f761758 sp=0xc03f761710 pc=0xd3ee72
github.com/grafana/sobek.(*baseJsFuncObject).__call(0xc03ea7bc80, {0xc02d995ae0?, 0x1, 0x480?}, {0x0, 0x0}, {0x1dc5bc8?, 0x2ef2c40?})
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/func.go:426 +0x705 fp=0xc03f761868 sp=0xc03f761758 pc=0xcdb145
github.com/grafana/sobek.(*baseJsFuncObject)._call(...)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/func.go:442
github.com/grafana/sobek.(*baseJsFuncObject).call(0x1fe64384ad8?, {{0x1dc5bc8, 0x2ef2c40}, {0xc02d995ae0, 0x1, 0x1}}, {0x0?, 0x0?})
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/func.go:450 +0x76 fp=0xc03f7618b8 sp=0xc03f761868 pc=0xcdb556
github.com/grafana/sobek.(*baseJsFuncObject).Call(...)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/func.go:382
github.com/grafana/sobek.(*baseJsFuncObject).Call-fm({{0x1dc5bc8, 0x2ef2c40}, {0xc02d995ae0, 0x1, 0x1}})
        <autogenerated>:1 +0x90 fp=0xc03f761930 sp=0xc03f7618b8 pc=0xd80850
github.com/grafana/sobek.AssertFunction.func1.1()
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/runtime.go:2481 +0x56 fp=0xc03f761998 sp=0xc03f761930 pc=0xd26096
github.com/grafana/sobek.(*vm).try(0xc03ea779e0, 0xc03f761af0)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/vm.go:870 +0x23c fp=0xc03f761a78 sp=0xc03f761998 pc=0xd3e9fc
github.com/grafana/sobek.(*Runtime).runWrapped(0xc03f70c408, 0x87679?)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/runtime.go:2525 +0x5f fp=0xc03f761ad0 sp=0xc03f761a78 pc=0xd2637f
github.com/grafana/sobek.AssertFunction.func1({0x1dc5bc8?, 0x2ef2c40?}, {0xc02d995ae0?, 0x1?, 0x1?})
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/runtime.go:2480 +0x8c fp=0xc03f761b40 sp=0xc03f761ad0 pc=0xd25fcc
go.k6.io/k6/internal/js.(*VU).runFn.func2()
        go.k6.io/k6/internal/js/runner.go:915 +0x3e fp=0xc03f761b80 sp=0xc03f761b40 pc=0x1495d7e
go.k6.io/k6/internal/js/eventloop.(*EventLoop).Start(0xc03a8f1b80, 0xc038bc0360)
        go.k6.io/k6/internal/js/eventloop/eventloop.go:177 +0x197 fp=0xc03f761c68 sp=0xc03f761b80 pc=0xdcdf57
go.k6.io/k6/internal/js.(*VU).runFn(0xc040c5b9a0, {0x1dae8a8, 0xc03a6b8410}, 0x1, 0xc0307400d8, 0xc02d995ac0, {0xc02d995ae0, 0x1, 0x1})
        go.k6.io/k6/internal/js/runner.go:914 +0x269 fp=0xc03f761d68 sp=0xc03f761c68 pc=0x14958c9
go.k6.io/k6/internal/js.(*ActiveVU).RunOnce(0xc03e9b9e40)
        go.k6.io/k6/internal/js/runner.go:847 +0x48f fp=0xc03f761ee0 sp=0xc03f761d68 pc=0x149518f
go.k6.io/k6/lib/executor.RampingArrivalRate.Run.getIterationRunner.func8({0x1dae870, 0xc0119da030}, {0x1d98080?, 0xc03e9b9e40?})
        go.k6.io/k6/lib/executor/helpers.go:108 +0x4a fp=0xc03f761f58 sp=0xc03f761ee0 pc=0x70752a
go.k6.io/k6/lib/executor.(*activeVUPool).AddVU.func1()
        go.k6.io/k6/lib/executor/ramping_arrival_rate.go:546 +0xd5 fp=0xc03f761fe0 sp=0xc03f761f58 pc=0x707f75
runtime.goexit({})
        runtime/asm_amd64.s:1700 +0x1 fp=0xc03f761fe8 sp=0xc03f761fe0 pc=0x92361
created by go.k6.io/k6/lib/executor.(*activeVUPool).AddVU in goroutine 1235
        go.k6.io/k6/lib/executor/ramping_arrival_rate.go:539 +0xef

goroutine 62539 gp=0xc03ea3c8c0 m=nil [runnable]:
runtime.cgocall(0x93b80, 0xc03f846348)
        runtime/cgocall.go:167 +0x3e fp=0xc03fa07038 sp=0xc03fa06fd0 pc=0x86b3e
runtime.syscall_syscalln(0x22c8c0?, 0xc02f409cf0?, {0xc03fa07080?, 0x0?, 0x0?})
        runtime/syscall_windows.go:521 +0x4e fp=0xc03fa07058 sp=0xc03fa07038 pc=0x73a2e
syscall.Syscall(0xc03fa07180?, 0x1fe62d6e800?, 0xc03fa070d8?, 0x89005?, 0x2ef37a0?)
        runtime/syscall_windows.go:457 +0x29 fp=0xc03fa070a8 sp=0xc03fa07058 pc=0x8dec9
syscall.Closesocket(0x1d378)
        syscall/zsyscall_windows.go:1342 +0x4f fp=0xc03fa070e8 sp=0xc03fa070a8 pc=0xb6def
internal/poll.(*FD).destroy(0xc03f73c288)
        internal/poll/fd_windows.go:372 +0x63 fp=0xc03fa07110 sp=0xc03fa070e8 pc=0xf1023
internal/poll.(*FD).decref(0x1fe62d6e7d0?)
        internal/poll/fd_mutex.go:213 +0x53 fp=0xc03fa07130 sp=0xc03fa07110 pc=0xeefd3
internal/poll.(*FD).Close(0xc03f73c288)
        internal/poll/fd_windows.go:392 +0x65 fp=0xc03fa07160 sp=0xc03fa07130 pc=0xf1105
net.(*netFD).Close(0xc03f73c288)
        net/fd_posix.go:37 +0x32 fp=0xc03fa07190 sp=0xc03fa07160 pc=0x22aa32
net.socket({0x1dae918, 0xc02a804e00}, {0x19ed61e, 0x3}, 0x2, 0x1, 0xc03fa072e8?, 0x0, {0x1db5df8, 0x0}, ...)
        net/sock_posix.go:71 +0x2c8 fp=0xc03fa07238 sp=0xc03fa07190 pc=0x2443a8
net.internetSocket({0x1dae918, 0xc02a804e00}, {0x19ed61e, 0x3}, {0x1db5df8, 0x0}, {0x1db5df8?, 0xc03f72dd70?}, 0x1, 0x0, ...)
        net/ipsock_posix.go:167 +0x1e5 fp=0xc03fa072c0 sp=0xc03fa07238 pc=0x235005
net.(*sysDialer).doDialTCPProto(0xc03f732cc0, {0x1dae918, 0xc02a804e00}, 0x0, 0xc03f72dd70, 0x0)
        net/tcpsock_posix.go:85 +0xe7 fp=0xc03fa07370 sp=0xc03fa072c0 pc=0x247ea7
net.(*sysDialer).doDialTCP(...)
        net/tcpsock_posix.go:75
net.(*sysDialer).dialTCP(0xc03f72dd70?, {0x1dae918?, 0xc02a804e00?}, 0x166dd20?, 0xc03fa07448?)
        net/tcpsock_posix.go:71 +0x69 fp=0xc03fa073b0 sp=0xc03fa07370 pc=0x247d49
net.(*sysDialer).dialSingle(0xc03f732cc0, {0x1dae918, 0xc02a804e00}, {0x1da5628, 0xc03f72dd70})
        net/dial.go:721 +0x3ce fp=0xc03fa07480 sp=0xc03fa073b0 pc=0x2224ae
net.(*sysDialer).dialSerial(0xc03f732cc0, {0x1dae918, 0xc02a804e00}, {0xc02f409ce0?, 0x1, 0xc03f72dd40?})
        net/dial.go:686 +0x24e fp=0xc03fa07588 sp=0xc03fa07480 pc=0x221c8e
net.(*sysDialer).dialParallel(0x0?, {0x1dae918?, 0xc02a804e00?}, {0xc02f409ce0?, 0x1747280?, 0x19edf53?}, {0x0?, 0x19ed61e?, 0xc036871af0?})
        net/dial.go:587 +0x3a7 fp=0xc03fa077a0 sp=0xc03fa07588 pc=0x221367
net.(*Dialer).DialContext(0xc03cff17a0, {0x1dae8a8, 0xc03b079040}, {0x19ed61e, 0x3}, {0xc036871b00, 0xe})
        net/dial.go:578 +0x6ac fp=0xc03fa07910 sp=0xc03fa077a0 pc=0x220bac
go.k6.io/k6/lib/netext.(*Dialer).DialContext(0xc03cff17a0, {0x1dae8a8, 0xc03b079040}, {0x19ed61e, 0x3}, {0xc036871ad0?, 0xd01f8?})
        go.k6.io/k6/lib/netext/dialer.go:64 +0x7d fp=0xc03fa07978 sp=0xc03fa07910 pc=0xa432fd
go.k6.io/k6/lib/netext.(*Dialer).DialContext-fm({0x1dae8a8?, 0xc03b079040?}, {0x19ed61e?, 0xc03f72db30?}, {0xc036871ad0?, 0xc014841a18?})
        <autogenerated>:1 +0x49 fp=0xc03fa079c0 sp=0xc03fa07978 pc=0x1498529
net/http.(*Transport).dial(0x0?, {0x1dae8a8?, 0xc03b079040?}, {0x19ed61e?, 0xfffffffffffffffe?}, {0xc036871ad0?, 0xc014841a10?})
        net/http/transport.go:1278 +0xd2 fp=0xc03fa07a28 sp=0xc03fa079c0 pc=0x385712
net/http.(*Transport).dialConn(0xc03e0b2340, {0x1dae8a8, 0xc03b079040}, {{}, 0x0, {0xc000481f80, 0x4}, {0xc036871ad0, 0xe}, 0x0})
        net/http/transport.go:1780 +0x7e5 fp=0xc03fa07ee0 sp=0xc03fa07a28 pc=0x3886e5
net/http.(*Transport).dialConnFor(0xc03e0b2340, 0xc02b3811e0)
        net/http/transport.go:1615 +0xb8 fp=0xc03fa07f90 sp=0xc03fa07ee0 pc=0x3871f8
net/http.(*Transport).startDialConnForLocked.func1()
        net/http/transport.go:1597 +0x35 fp=0xc03fa07fe0 sp=0xc03fa07f90 pc=0x387035
runtime.goexit({})
        runtime/asm_amd64.s:1700 +0x1 fp=0xc03fa07fe8 sp=0xc03fa07fe0 pc=0x92361
created by net/http.(*Transport).startDialConnForLocked in goroutine 62643
        net/http/transport.go:1596 +0x112

goroutine 62389 gp=0xc037199c00 m=nil [runnable]:
runtime.cgocall(0x93b80, 0xc03dec2348)
        runtime/cgocall.go:167 +0x3e fp=0xc03fa27038 sp=0xc03fa26fd0 pc=0x86b3e
runtime.syscall_syscalln(0x22c8c0?, 0xc02d995c40?, {0xc03fa27080?, 0x0?, 0x0?})
        runtime/syscall_windows.go:521 +0x4e fp=0xc03fa27058 sp=0xc03fa27038 pc=0x73a2e
syscall.Syscall(0xc03fa27180?, 0x1fe63747948?, 0xc03fa270d8?, 0x89005?, 0x2ef37a0?)
        runtime/syscall_windows.go:457 +0x29 fp=0xc03fa270a8 sp=0xc03fa27058 pc=0x8dec9
syscall.Closesocket(0x1d00c)
        syscall/zsyscall_windows.go:1342 +0x4f fp=0xc03fa270e8 sp=0xc03fa270a8 pc=0xb6def
internal/poll.(*FD).destroy(0xc037d61408)
        internal/poll/fd_windows.go:372 +0x63 fp=0xc03fa27110 sp=0xc03fa270e8 pc=0xf1023
internal/poll.(*FD).decref(0x1fe63747918?)
        internal/poll/fd_mutex.go:213 +0x53 fp=0xc03fa27130 sp=0xc03fa27110 pc=0xeefd3
internal/poll.(*FD).Close(0xc037d61408)
        internal/poll/fd_windows.go:392 +0x65 fp=0xc03fa27160 sp=0xc03fa27130 pc=0xf1105
net.(*netFD).Close(0xc037d61408)
        net/fd_posix.go:37 +0x32 fp=0xc03fa27190 sp=0xc03fa27160 pc=0x22aa32
net.socket({0x1dae918, 0xc023701ce0}, {0x19ed61e, 0x3}, 0x2, 0x1, 0xc03fa272e8?, 0x0, {0x1db5df8, 0x0}, ...)
        net/sock_posix.go:71 +0x2c8 fp=0xc03fa27238 sp=0xc03fa27190 pc=0x2443a8
net.internetSocket({0x1dae918, 0xc023701ce0}, {0x19ed61e, 0x3}, {0x1db5df8, 0x0}, {0x1db5df8?, 0xc038bc0780?}, 0x1, 0x0, ...)
        net/ipsock_posix.go:167 +0x1e5 fp=0xc03fa272c0 sp=0xc03fa27238 pc=0x235005
net.(*sysDialer).doDialTCPProto(0xc038baafc0, {0x1dae918, 0xc023701ce0}, 0x0, 0xc038bc0780, 0x0)
        net/tcpsock_posix.go:85 +0xe7 fp=0xc03fa27370 sp=0xc03fa272c0 pc=0x247ea7
net.(*sysDialer).doDialTCP(...)
        net/tcpsock_posix.go:75
net.(*sysDialer).dialTCP(0xc038bc0780?, {0x1dae918?, 0xc023701ce0?}, 0x166dd20?, 0xc03fa27448?)
        net/tcpsock_posix.go:71 +0x69 fp=0xc03fa273b0 sp=0xc03fa27370 pc=0x247d49
net.(*sysDialer).dialSingle(0xc038baafc0, {0x1dae918, 0xc023701ce0}, {0x1da5628, 0xc038bc0780})
        net/dial.go:721 +0x3ce fp=0xc03fa27480 sp=0xc03fa273b0 pc=0x2224ae
net.(*sysDialer).dialSerial(0xc038baafc0, {0x1dae918, 0xc023701ce0}, {0xc02d995c30?, 0x1, 0xc038bc0750?})
        net/dial.go:686 +0x24e fp=0xc03fa27588 sp=0xc03fa27480 pc=0x221c8e
net.(*sysDialer).dialParallel(0x0?, {0x1dae918?, 0xc023701ce0?}, {0xc02d995c30?, 0x1747280?, 0x19edf53?}, {0x0?, 0x19ed61e?, 0xc038040db0?})
        net/dial.go:587 +0x3a7 fp=0xc03fa277a0 sp=0xc03fa27588 pc=0x221367
net.(*Dialer).DialContext(0xc03d679ea0, {0x1dae8a8, 0xc03a6b85a0}, {0x19ed61e, 0x3}, {0xc038040dc0, 0xe})
        net/dial.go:578 +0x6ac fp=0xc03fa27910 sp=0xc03fa277a0 pc=0x220bac
go.k6.io/k6/lib/netext.(*Dialer).DialContext(0xc03d679ea0, {0x1dae8a8, 0xc03a6b85a0}, {0x19ed61e, 0x3}, {0xc038040d90?, 0xd01f8?})
        go.k6.io/k6/lib/netext/dialer.go:64 +0x7d fp=0xc03fa27978 sp=0xc03fa27910 pc=0xa432fd
go.k6.io/k6/lib/netext.(*Dialer).DialContext-fm({0x1dae8a8?, 0xc03a6b85a0?}, {0x19ed61e?, 0xc038bc0540?}, {0xc038040d90?, 0xc01997ba18?})
        <autogenerated>:1 +0x49 fp=0xc03fa279c0 sp=0xc03fa27978 pc=0x1498529
net/http.(*Transport).dial(0x0?, {0x1dae8a8?, 0xc03a6b85a0?}, {0x19ed61e?, 0xfffffffffffffffe?}, {0xc038040d90?, 0xc01997ba10?})
        net/http/transport.go:1278 +0xd2 fp=0xc03fa27a28 sp=0xc03fa279c0 pc=0x385712
net/http.(*Transport).dialConn(0xc03d5cb1e0, {0x1dae8a8, 0xc03a6b85a0}, {{}, 0x0, {0xc000481f80, 0x4}, {0xc038040d90, 0xe}, 0x0})
        net/http/transport.go:1780 +0x7e5 fp=0xc03fa27ee0 sp=0xc03fa27a28 pc=0x3886e5
net/http.(*Transport).dialConnFor(0xc03d5cb1e0, 0xc023b9c790)
        net/http/transport.go:1615 +0xb8 fp=0xc03fa27f90 sp=0xc03fa27ee0 pc=0x3871f8
net/http.(*Transport).startDialConnForLocked.func1()
        net/http/transport.go:1597 +0x35 fp=0xc03fa27fe0 sp=0xc03fa27f90 pc=0x387035
runtime.goexit({})
        runtime/asm_amd64.s:1700 +0x1 fp=0xc03fa27fe8 sp=0xc03fa27fe0 pc=0x92361
created by net/http.(*Transport).startDialConnForLocked in goroutine 62538
        net/http/transport.go:1596 +0x112

goroutine 62430 gp=0xc03ca86540 m=nil [select, 2 minutes]:
runtime.gopark(0xc03fa22190?, 0x2?, 0xd2?, 0x6f?, 0xc03fa220c4?)
        runtime/proc.go:435 +0xce fp=0xc03fa21f50 sp=0xc03fa21f30 pc=0x89fce
runtime.selectgo(0xc03fa22190, 0xc03fa220c0, 0xe?, 0x0, 0x1888a?, 0x1)
        runtime/select.go:351 +0x837 fp=0xc03fa22088 sp=0xc03fa21f50 pc=0x69197
net/http.(*Transport).getConn(0xc0386d1860, 0xc03ad86320, {{}, 0x0, {0xc000481f80, 0x4}, {0xc03e5a4480, 0xe}, 0x0})
        net/http/transport.go:1520 +0x4ae fp=0xc03fa22260 sp=0xc03fa22088 pc=0x3866ce
net/http.(*Transport).roundTrip(0xc0386d1860, 0xc02e1a08c0)
        net/http/transport.go:685 +0xb57 fp=0xc03fa22458 sp=0xc03fa22260 pc=0x3823f7
net/http.(*Transport).RoundTrip(0x1dae918?, 0xc027ff2850?)
        net/http/roundtrip.go:30 +0x13 fp=0xc03fa22478 sp=0xc03fa22458 pc=0x391733
go.k6.io/k6/lib/netext/httpext.(*transport).RoundTrip(0xc03f69a700, 0xc02e1a0780)
        go.k6.io/k6/lib/netext/httpext/transport.go:205 +0x474 fp=0xc03fa22568 sp=0xc03fa22478 pc=0xa533b4
net/http.send(0xc02e1a0780, {0x1d9e1c0, 0xc03f69a700}, {0xc03fa22701?, 0x73e0c?, 0x0?})
        net/http/client.go:259 +0x5e2 fp=0xc03fa22758 sp=0xc03fa22568 pc=0x31dc02
net/http.(*Client).send(0xc03f6b3ec0, 0xc02e1a0780, {0xc027ff29b0?, 0x27d91?, 0x0?})
        net/http/client.go:180 +0x91 fp=0xc03fa227d0 sp=0xc03fa22758 pc=0x31d4b1
net/http.(*Client).do(0xc03f6b3ec0, 0xc02e1a0780)
        net/http/client.go:728 +0x989 fp=0xc03fa229c0 sp=0xc03fa227d0 pc=0x31fac9
net/http.(*Client).Do(...)
        net/http/client.go:587
go.k6.io/k6/lib/netext/httpext.MakeRequest({0x1dae8a8, 0xc03b001ea0}, 0xc039940e08, 0xc03f6acea0)
        go.k6.io/k6/lib/netext/httpext/request.go:265 +0x11c5 fp=0xc03fa22d50 sp=0xc03fa229c0 pc=0xa4f465
go.k6.io/k6/js/modules/k6/http.(*Client).Request(0xc02d87fab0, {0x19ed5d3, 0x3}, {0x1dc5968, 0xc000297430}, {0xc03fa22e20, 0x1, 0x1})
        go.k6.io/k6/js/modules/k6/http/request.go:51 +0xfc fp=0xc03fa22dc0 sp=0xc03fa22d50 pc=0x11bb2dc
go.k6.io/k6/js/modules/k6/http.(*RootModule).NewModuleInstance.func2({0x1dc5968, 0xc000297430}, {0x2ef2c40?, 0x2?, 0x0?})
        go.k6.io/k6/js/modules/k6/http/http.go:75 +0x11e fp=0xc03fa22e40 sp=0xc03fa22dc0 pc=0x11ba5de
runtime.call64(0xc011cac210, 0xc02d87fb90, 0x0, 0x0, 0x0, 0x28, 0xc03fa230c8)
        runtime/asm_amd64.s:777 +0x48 fp=0xc03fa22e90 sp=0xc03fa22e40 pc=0x909a8
runtime.reflectcall(0x1643040?, 0xc036d8c7c8?, 0x8?, 0x1a0a0cc?, 0x0?, 0x12?, 0x1643040?)
        <autogenerated>:1 +0x36 fp=0xc03fa22ed0 sp=0xc03fa22e90 pc=0x97396
reflect.Value.call({0x170d080?, 0xc02d87fb90?, 0xc03fa23458?}, {0x19edf6b, 0x4}, {0xc036d8c7b0, 0x1, 0xc03fa23480?})
        reflect/value.go:584 +0xca6 fp=0xc03fa23418 sp=0xc03fa22ed0 pc=0x12a5a6
reflect.Value.Call({0x170d080?, 0xc02d87fb90?, 0xc000297430?}, {0xc036d8c7b0?, 0xc02ee5ba60?, 0x10?})
        reflect/value.go:368 +0xb9 fp=0xc03fa23490 sp=0xc03fa23418 pc=0x1296b9
github.com/grafana/sobek.(*Runtime).newWrappedFunc.(*Runtime).wrapReflectFunc.func1({{0x1dc55d8, 0xc03fa82bd0}, {0xc03f6af3f0, 0x1, 0x5}})
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/runtime.go:2040 +0x3bd fp=0xc03fa235e8 sp=0xc03fa23490 pc=0xd1cbfd
github.com/grafana/sobek.(*nativeFuncObject).vmCall(0xc03ca93bc0, 0xc03c9610e0, 0x1)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/func.go:563 +0x183 fp=0xc03fa23670 sp=0xc03fa235e8 pc=0xcdc223
github.com/grafana/sobek.call.exec(0x3?, 0xc03c9610e0)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/vm.go:3732 +0x66 fp=0xc03fa236a0 sp=0xc03fa23670 pc=0xd52b26
github.com/grafana/sobek.(*call).exec(0x800000000000000?, 0xc03c9610e0?)
        <autogenerated>:1 +0x25 fp=0xc03fa236c0 sp=0xc03fa236a0 pc=0xdaa1c5
github.com/grafana/sobek.(*vm).run(0xc03c9610e0)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/vm.go:642 +0x5b fp=0xc03fa23710 sp=0xc03fa236c0 pc=0xd3d47b
github.com/grafana/sobek.(*vm).runTryInner(0xc03c9610e0?)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/vm.go:893 +0x52 fp=0xc03fa23758 sp=0xc03fa23710 pc=0xd3ee72
github.com/grafana/sobek.(*baseJsFuncObject).__call(0xc03ca93980, {0xc02ee5ba40?, 0x1, 0x480?}, {0x0, 0x0}, {0x1dc5bc8?, 0x2ef2c40?})
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/func.go:426 +0x705 fp=0xc03fa23868 sp=0xc03fa23758 pc=0xcdb145
github.com/grafana/sobek.(*baseJsFuncObject)._call(...)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/func.go:442
github.com/grafana/sobek.(*baseJsFuncObject).call(0x1fe6376c938?, {{0x1dc5bc8, 0x2ef2c40}, {0xc02ee5ba40, 0x1, 0x1}}, {0x0?, 0x0?})
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/func.go:450 +0x76 fp=0xc03fa238b8 sp=0xc03fa23868 pc=0xcdb556
github.com/grafana/sobek.(*baseJsFuncObject).Call(...)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/func.go:382
github.com/grafana/sobek.(*baseJsFuncObject).Call-fm({{0x1dc5bc8, 0x2ef2c40}, {0xc02ee5ba40, 0x1, 0x1}})
        <autogenerated>:1 +0x90 fp=0xc03fa23930 sp=0xc03fa238b8 pc=0xd80850
github.com/grafana/sobek.AssertFunction.func1.1()
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/runtime.go:2481 +0x56 fp=0xc03fa23998 sp=0xc03fa23930 pc=0xd26096
github.com/grafana/sobek.(*vm).try(0xc03c9610e0, 0xc03fa23af0)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/vm.go:870 +0x23c fp=0xc03fa23a78 sp=0xc03fa23998 pc=0xd3e9fc
github.com/grafana/sobek.(*Runtime).runWrapped(0xc039f5d808, 0x87679?)
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/runtime.go:2525 +0x5f fp=0xc03fa23ad0 sp=0xc03fa23a78 pc=0xd2637f
github.com/grafana/sobek.AssertFunction.func1({0x1dc5bc8?, 0x2ef2c40?}, {0xc02ee5ba40?, 0x1?, 0x1?})
        github.com/grafana/sobek@v0.0.0-20250320150027-203dc85b6d98/runtime.go:2480 +0x8c fp=0xc03fa23b40 sp=0xc03fa23ad0 pc=0xd25fcc
go.k6.io/k6/internal/js.(*VU).runFn.func2()
        go.k6.io/k6/internal/js/runner.go:915 +0x3e fp=0xc03fa23b80 sp=0xc03fa23b40 pc=0x1495d7e
go.k6.io/k6/internal/js/eventloop.(*EventLoop).Start(0xc03a4fb4a0, 0xc03f6b3d70)
        go.k6.io/k6/internal/js/eventloop/eventloop.go:177 +0x197 fp=0xc03fa23c68 sp=0xc03fa23b80 pc=0xdcdf57
go.k6.io/k6/internal/js.(*VU).runFn(0xc040491180, {0x1dae8a8, 0xc03b001ea0}, 0x1, 0xc03
    */